Updated nextflow to 0.26 and tested ./make_database.sh with feature_test

diff --git a/workflow/nextflow b/workflow/nextflow
--- a/workflow/nextflow
+++ b/workflow/nextflow
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
-#  Copyright (c) 2013-2016, Centre for Genomic Regulation (CRG).
-#  Copyright (c) 2013-2016, Paolo Di Tommaso and the respective authors.
+#  Copyright (c) 2013-2017, Centre for Genomic Regulation (CRG).
+#  Copyright (c) 2013-2017, Paolo Di Tommaso and the respective authors.
 #
 #  This file is part of Nextflow.
 #
@@ -18,15 +18,29 @@
 #  You should have received a copy of the GNU General Public License
 #  along with Nextflow.  If not, see <http://www.gnu.org/licenses/>.
 
+[[ "$NXF_DEBUG" == 'x' ]] && set -x
+NXF_VER=${NXF_VER:-'0.26.0'}
+NXF_ORG=${NXF_ORG:-'nextflow-io'}
+NXF_HOME=${NXF_HOME:-$HOME/.nextflow}
+NXF_PROT=${NXF_PROT:-'https'}
+NXF_BASE=${NXF_BASE:-$NXF_PROT://www.nextflow.io/releases}
+NXF_CLI="$0 $@"
+
+export NXF_CLI
+export NXF_ORG
+export NXF_HOME
+
 if [[ $TERM && $TERM != 'dumb' ]]; then
+if command -v tput &>/dev/null; then
 GREEN=$(tput setaf 2; tput bold)
 YELLOW=$(tput setaf 3)
 RED=$(tput setaf 1)
 NORMAL=$(tput sgr0)
 fi
+fi
 
 function echo_red() {
-    echo -e "$RED$*$NORMAL"
+    >&2 echo -e "$RED$*$NORMAL"
 }
 
 function echo_green() {
@@ -34,7 +48,7 @@ function echo_green() {
 }
 
 function echo_yellow() {
-    echo -e "$YELLOW$*$NORMAL"
+    >&2 echo -e "$YELLOW$*$NORMAL"
 }
 
 function die() {
@@ -42,17 +56,17 @@ function die() {
   exit 1
 }
 
-get_abs_filename() {
+function get_abs_filename() {
   echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
 }
 
 function get() {
-    if command -v wget &>/dev/null; then
-        GET="wget -q $1 -O $2"
-    elif command -v curl &>/dev/null; then
+    if command -v curl &>/dev/null; then
         GET="curl -fsSL $1 -o $2"
+    elif command -v wget &>/dev/null; then
+        GET="wget -q $1 -O $2"
     else
-        echo_red "Error: cannot find 'curl' nor 'wget' utility --  please install one of them"
+        echo_red "ERROR: Cannot find 'curl' nor 'wget' utility --  please install one of them"
         exit 1
     fi
 
@@ -60,12 +74,12 @@ function get() {
     $GET; status=$?
     printf "\r\033[K"
     if [ $status -ne 0 ]; then
-        echo_red "Error: cannot download nextflow required file -- make sure you can connect the internet"
+        echo_red "ERROR: Cannot download nextflow required file -- make sure you can connect to the internet"
         echo ""
-        echo "Alternatively you can download the file:"
+        echo "Alternatively you can try to download this file:"
         echo "    $1"
         echo ""
-        echo "And save it as:"
+        echo "and save it as:"
         echo "    ${3:-$2}"
         echo ""
         exit 1
@@ -74,14 +88,26 @@ function get() {
 
 function make_temp() {
     local base=${NXF_TEMP:=$PWD}
-    if [ "$(uname)" = 'Darwin' ]; then mktemp ${base}/nxf-tmp.XXXXX || exit $?
-    else mktemp -t nxf-tmp.XXXXX -p ${base} || exit $?
+    if [ "$(uname)" = 'Darwin' ]; then mktemp "${base}/nxf-tmp.XXXXX" || exit $?
+    else mktemp -t nxf-tmp.XXXXX -p "${base}" || exit $?
+    fi
+}
+
+function resolve_link() {
+    if command -v realpath &>/dev/null; then
+      realpath $1
+    elif command -v readlink &>/dev/null; then
+      readlink -f $1
+    else
+      echo_yellow "WARN: Neither \`realpath\` nor \`readlink\` command can be found"
+      exit 1
     fi
 }
 
 function install() {
     local tmpfile=$(make_temp)
-    get "http://www.nextflow.io/releases/latest/nextflow" "$tmpfile" "$1" || exit $?
+    local version=$(set +u; [[ $NXF_VER ]] && printf "v$NXF_VER" || printf 'latest')
+    get "$NXF_BASE/$version/nextflow" "$tmpfile" "$1" || exit $?
     mv "$tmpfile" "$1" || exit $?
     chmod +x "$1" || exit $?
     bash "$1" -download || exit $?
@@ -102,21 +128,31 @@ function launch_nextflow() {
     done
 
     if [[ $NXF_MPIRUN ]]; then
-        if [[ -z $OMPI_COMM_WORLD_RANK ]]; then echo_red 'Missing `$OMPI_COMM_WORLD_RANK` variable -- it looks you are not running in a MPI environment'; exit 1; fi
-        if [[ $OMPI_COMM_WORLD_RANK == 0 ]]; then
+        local rank=''
+        [[ $SLURM_PROCID ]] && rank=$SLURM_PROCID
+        [[ $OMPI_COMM_WORLD_RANK ]] && rank=$OMPI_COMM_WORLD_RANK
+        if [[ ! $rank ]]; then
+          echo_red 'It looks you are not running in a MPI enabled environment -- cannot find `$OMPI_COMM_WORLD_RANK` nor `$SLURM_PROCID` variable';
+          exit 1;
+        fi
+        if [[ $SLURM_CPUS_PER_TASK && $SLURM_MEM_PER_CPU ]]; then
+            export NXF_CLUSTER_MAXCPUS=$SLURM_CPUS_PER_TASK
+            export NXF_CLUSTER_MAXMEMORY="$(($SLURM_MEM_PER_CPU*$SLURM_CPUS_PER_TASK))MB"
+        fi
+        if [[ $rank == 0 ]]; then
             # sleep a few seconds in order to wait worker daemons to bootstrap
             sleep ${NXF_SLEEP:-10}
             export NXF_EXECUTOR='ignite'
             export NXF_CLUSTER_SHUTDOWNONCOMPLETE='true'
         else
-            cmdline="${launcher[@]} -log .nextflow_node_${HOSTNAME}_${OMPI_COMM_WORLD_RANK}.log node ignite"
+            cmdline="${launcher[@]} -log .nextflow_node_${rank}.log node ignite"
         fi
     # start in daemon mode
     elif [[ "$bg" ]]; then
       local pid_file="${NXF_PID_FILE:-.nextflow.pid}"
       bash -c "exec $cmdline" &
       disown
-      printf $! > "$pid_file"
+      echo $! > "$pid_file"
       exit 0
     fi
 
@@ -138,17 +174,8 @@ if [ "$0" = "bash" ] || [ "$0" = "/bin/bash" ]; then
     exit 0
 fi
 
-NXF_HOME=${NXF_HOME:-$HOME/.nextflow}
-NXF_VER=${NXF_VER:-'0.23.4'}
-NXF_ORG=${NXF_ORG:-'nextflow-io'}
-NXF_ASSETS=${NXF_ASSETS:-$NXF_HOME/assets}
-NXF_CLI="$0 $@"
 
-export NXF_CLI
-export NXF_ORG
-export NXF_HOME
-
-# Check if it is required to run in background
+# parse the command line
 bg=''
 declare -a jvmopts=()
 declare -a args=("$@")
@@ -166,14 +193,15 @@ while [[ $# != 0 ]]; do
       ;;
     -download)
       if [[ ! "$cmd" ]]; then
-      rm -rf $NXF_HOME/framework/$NXF_VER || exit $?
-      $0 -version || exit $?
+      rm -rf "$NXF_HOME/framework/$NXF_VER" || exit $?
+      bash "$0" -version || exit $?
       exit 0
       fi
       ;;
     -self-update|self-update)
       if [[ ! "$cmd" ]]; then
-      install $0;
+      unset NXF_VER
+      install "$0";
       exit 0
       fi
       ;;
@@ -211,7 +239,6 @@ NXF_PACK=one
 NXF_MODE=${NXF_MODE:-''}
 NXF_JAR=${NXF_JAR:-nextflow-$NXF_VER-$NXF_PACK.jar}
 NXF_BIN=${NXF_BIN:-$NXF_HOME/framework/$NXF_VER/$NXF_JAR}
-NXF_BASE=${NXF_BASE:-http://www.nextflow.io/releases}
 NXF_PATH=$(dirname "$NXF_BIN")
 NXF_URL=${NXF_URL:-$NXF_BASE/v$NXF_VER/$NXF_JAR}
 NXF_GRAB=${NXF_GRAB:-''}
@@ -249,14 +276,29 @@ if [ ! -x "$JAVA_CMD" ] ; then
     fi
 fi
 
-# Verify installed Java version
-if [ ! -d "$NXF_LAUNCHER" ]; then # <-- only the first time
-    $JAVA_CMD -version 2>&1 | awk '/version/ {print $3}' | grep '"1\.[7|8]\..*"' > /dev/null
-    if [ $? -ne 0 ]; then
-         echo_red "Error: cannot find Java or it's a wrong version -- please make sure that Java 7 or higher it's installed"
-         echo_red "Note: Nextflow is trying to use the Java VM defined by the following environment variables:\n JAVA_CMD: $JAVA_CMD\n JAVA_HOME: $JAVA_HOME\n"
-         exit 1
-    fi
+# Retrieve the java version from a NF local file
+JAVA_KEY="$NXF_HOME/tmp/ver/$(resolve_link $JAVA_CMD | sed 's@/@.@g')"
+if [ -f $JAVA_KEY ]; then
+  JAVA_VER="$(cat $JAVA_KEY)"
+else
+  JAVA_VER="$($JAVA_CMD $NXF_OPTS -version 2>&1)"
+  if [ $? -ne 0 ]; then
+      echo_red "${JAVA_VER:-Failed to launch the Java virtual machine}"
+      echo_yellow "NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:\n JAVA_CMD: $JAVA_CMD\n NXF_OPTS: $NXF_OPTS\n"
+      exit 1
+  fi
+  JAVA_VER=$(echo "$JAVA_VER" | awk '/version/ {gsub(/"/, "", $3); print $3}')
+  if [[ ! $JAVA_VER =~ ^1.8 && ! $JAVA_VER =~ ^9 ]]; then
+      echo_red "ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 is installed"
+      echo_yellow "NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:\n JAVA_CMD: $JAVA_CMD\n JAVA_HOME: $JAVA_HOME\n"
+      exit 1
+  fi
+  mkdir -p $(dirname $JAVA_KEY)
+  [[ -f $JAVA_VER ]] && echo $JAVA_VER > $JAVA_KEY
+fi
+if [[ "$JAVA_VER" =~ ^9 ]]; then
+  echo_yellow "WARN: Nextflow support for Java 9 is still in beta stage and some advanced features are not supported"
+  echo_yellow "WARN: It is suggested the use of Java version 8"
 fi
 
 # Verify nextflow jar is available
@@ -264,7 +306,7 @@ if [ ! -f "$NXF_BIN" ]; then
     [ -f "$NXF_PATH" ] && rm "$NXF_PATH"
     mkdir -p "$NXF_PATH" || exit $?
     tmpfile=$(make_temp)
-    get "$NXF_URL" "$tmpfile"
+    get "$NXF_URL" "$tmpfile" "$NXF_BIN"
     mv "$tmpfile" "$NXF_BIN"
 fi
 
@@ -325,6 +367,7 @@ fi
 env_md5() {
 cat <<EOF | $MD5 | cut -f1 -d' '
 $JAVA_CMD
+$JAVA_VER
 $JAVA_OPTS
 $NXF_HOME
 $NXF_VER
@@ -341,11 +384,24 @@ if [ -s "$LAUNCH_FILE" ] && [ "$LAUNCH_FILE" -nt "$NXF_BIN" ]; then
     launcher=($(cat "$LAUNCH_FILE"))
 else
     # otherwise run the capsule and get the result classpath in the 'launcher' and save it to a file
-    launcher=($("$JAVA_CMD" $JAVA_OPTS -jar "$NXF_BIN"))
-    [[ $? -ne 0 ]] && echo 'Unable to initialize nextflow environment' && exit $?
+    cli=($("$JAVA_CMD" $JAVA_OPTS -jar "$NXF_BIN"))
+    [[ $? -ne 0 ]] && echo_red 'Unable to initialize nextflow environment' && exit $?
 
-    # Don't spit errors if can't create the LAUNCH_FILE
-    if mkdir -p ${NXF_LAUNCHER} 2>/dev/null; then
+    if [[ "$JAVA_VER" =~ ^9 ]]; then
+      echo_yellow "Nextflow support for Java 8 is still experimental an some advanced features are not yet supported -- Please use Java 8"
+      launcher=("${cli[@]:0:1}")
+      launcher+=(--add-opens=java.base/java.lang=ALL-UNNAMED)
+      launcher+=(--add-opens=java.base/java.io=ALL-UNNAMED)
+      launcher+=(--add-opens=java.base/java.util=ALL-UNNAMED)
+      launcher+=(--add-opens=java.base/sun.nio.ch=ALL-UNNAMED)
+      launcher+=(--illegal-access=deny)
+      launcher+=("${cli[@]:1}")
+    else
+      launcher=("${cli[@]}")
+    fi
+
+    # Don't show errors if the LAUNCH_FILE can't be created
+    if mkdir -p "${NXF_LAUNCHER}" 2>/dev/null; then
         STR=''
         for x in "${launcher[@]}"; do
         [[ "$x" != "\"-Duser.dir=$PWD\"" ]] && STR+="$x "
